package cli

import (
	"fmt"
	"os"
	"path/filepath"

	"gopkg.in/yaml.v3"
)

// Init generates a goalx.yaml template in the project root.
func Init(projectRoot string, args []string) error {
	if wantsHelp(args) {
		fmt.Println(launchUsage("init"))
		return nil
	}
	opts, err := parseStartInitArgs(args)
	if err != nil {
		return err
	}
	cfg, err := buildLaunchConfig(projectRoot, opts)
	if err != nil {
		return err
	}

	goalxDir := filepath.Join(projectRoot, ".goalx")
	os.MkdirAll(goalxDir, 0755)
	if err := EnsureProjectGoalxIgnored(projectRoot); err != nil {
		return fmt.Errorf("bootstrap .goalx ignore: %w", err)
	}
	outPath := filepath.Join(goalxDir, "goalx.yaml")
	data, err := yaml.Marshal(&cfg)
	if err != nil {
		return err
	}

	header := "# goalx.yaml — generated by goalx init\n# engine/model/master inherited from ~/.goalx/config.yaml and .goalx/config.yaml\n"
	if err := os.WriteFile(outPath, append([]byte(header), data...), 0644); err != nil {
		return err
	}

	fmt.Printf("Generated %s\n", outPath)
	fmt.Printf("  name: %s\n", cfg.Name)
	fmt.Printf("  mode: %s\n", cfg.Mode)
	if cfg.Mode == "develop" && (len(cfg.Target.Files) == 0 || cfg.Target.Files[0] == "TODO: specify directories to modify" || cfg.Harness.Command == "TODO: build + test command") {
		fmt.Println("\n  ⚠ Edit goalx.yaml: fill target.files and harness.command")
	}
	fmt.Println("\n  Next: vim goalx.yaml && goalx start")
	return nil
}
