package cli

import (
	"fmt"
	"os"
	"path/filepath"
	"time"

	goalx "github.com/vonbai/goalx"
	"gopkg.in/yaml.v3"
)

// Init generates a goalx.yaml template in the project root.
func Init(projectRoot string, args []string) error {
	opts, err := parseStartInitArgs(args)
	if err != nil {
		return err
	}
	objective := opts.Objective
	mode := opts.Mode
	parallel := opts.Parallel
	name := opts.Name

	if name == "" {
		name = goalx.Slugify(objective)
	}

	baseCfg, _, err := goalx.LoadRawBaseConfig(projectRoot)
	if err != nil {
		return fmt.Errorf("load base config: %w", err)
	}
	cfg := *baseCfg
	cfg.Name = name
	cfg.Mode = mode
	cfg.Objective = objective
	cfg.Parallel = parallel
	cfg.Sessions = nil
	cfg.DiversityHints = nil
	goalx.ApplyPreset(&cfg)

	// Mode-specific defaults
	if mode == goalx.ModeResearch {
		reportFile := "report.md"
		cfg.Target = goalx.TargetConfig{
			Files:    []string{reportFile},
			Readonly: []string{"."},
		}
		cfg.Harness = goalx.HarnessConfig{Command: fmt.Sprintf("test -s %s && echo 'ok'", cfg.Target.Files[0])}
		// Apply research strategies
		if len(opts.Strategies) > 0 {
			hints, err := goalx.ResolveStrategies(opts.Strategies)
			if err != nil {
				return err
			}
			cfg.DiversityHints = hints
		} else if parallel >= 2 {
			defaults := goalx.DefaultStrategies(parallel)
			hints, _ := goalx.ResolveStrategies(defaults)
			cfg.DiversityHints = hints
		}
	} else {
		if len(cfg.Target.Files) == 0 {
			cfg.Target = goalx.TargetConfig{
				Files: []string{"TODO: specify directories to modify"},
			}
		}
		if cfg.Harness.Command == "" {
			cfg.Harness = goalx.HarnessConfig{Command: "TODO: build + test command"}
		}
	}

	// Apply context from --context flag
	if len(opts.ContextPaths) > 0 {
		contextFiles, err := DiscoverContextFiles(opts.ContextPaths)
		if err != nil {
			return fmt.Errorf("discover context: %w", err)
		}
		cfg.Context = goalx.ContextConfig{Files: contextFiles}
	}

	cfg.Budget = goalx.BudgetConfig{MaxDuration: 6 * time.Hour}

	goalxDir := filepath.Join(projectRoot, ".goalx")
	os.MkdirAll(goalxDir, 0755)
	outPath := filepath.Join(goalxDir, "goalx.yaml")
	data, err := yaml.Marshal(&cfg)
	if err != nil {
		return err
	}

	header := "# goalx.yaml — generated by goalx init\n# engine/model/master inherited from ~/.goalx/config.yaml and .goalx/config.yaml\n"
	if err := os.WriteFile(outPath, append([]byte(header), data...), 0644); err != nil {
		return err
	}

	fmt.Printf("Generated %s\n", outPath)
	fmt.Printf("  name: %s\n", name)
	fmt.Printf("  mode: %s\n", mode)
	if mode == goalx.ModeDevelop && (len(cfg.Target.Files) == 0 || cfg.Target.Files[0] == "TODO: specify directories to modify" || cfg.Harness.Command == "TODO: build + test command") {
		fmt.Println("\n  ⚠ Edit goalx.yaml: fill target.files and harness.command")
	}
	fmt.Println("\n  Next: vim goalx.yaml && goalx start")
	return nil
}
